
const EVENTO_LOGIN = "LOGIN_GENERAL" ;
const EVENTO_LOGIN_ADMIN = "LOGIN_ADMIN";
const ID_CARGO_MENSUALIDAD = 1;

const CONSTANTES = {
    EVENTO_LOGIN : EVENTO_LOGIN,
    EVENTO_LOGIN_ADMIN : EVENTO_LOGIN_ADMIN,
    ID_CARGO_MENSUALIDAD : ID_CARGO_MENSUALIDAD,
    ID_CARGO_INCRIPCION : 2
};

export default CONSTANTES;